import assert from 'node:assert/strict';
import {validateReferences} from '../dist/references.js';
const a={type:'Model',slug:'coder',key:'models/coder',url:'https://knowledge.localllmfinder.com/models/coder/',entityIds:['model-11']};
assert.equal(validateReferences({version:1,articles:[a]}).get('Model:model-11').url,a.url);
assert.throws(()=>validateReferences({version:1,articles:[{...a,url:'javascript:alert(1)'}]}));
assert.throws(()=>validateReferences({version:1,articles:[a,a]}));
assert.equal(validateReferences({version:1,articles:[]}).size,0);
const dotted={...a,entityIds:['extra-glm-4.5-air'],status:'Draft'};
assert.equal(validateReferences({version:1,articles:[dotted]}).get('Model:extra-glm-4.5-air').status,'Draft');
for(const id of ['../escape','model"-7','extra..model','-model-7'])assert.throws(()=>validateReferences({version:1,articles:[{...a,entityIds:[id]}]}));
console.log('Reference URL validation, exact dotted catalogue IDs, draft mapping and unavailable references passed.');
